THEORY QUESTION

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?


Answer: The purpose and advantages of NumPy in scientific computing and data is - NumPy is ideal  for handling large amounts of homogenous data, offering significant improvements in speed and memory efficiency .

It enhance pythons  capabilities for numerical operations for making it a powerful tool for scientific computing and data processing on the CPU.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?


Answer:np.mean() is always compute arithmetic mean and have some additional options for input and output.

np.average()- it can compute a weighted average if the weights parameter is supplied.

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.


Answer: The methods for reversing a numpy array along different axes is-

1. list slincing technique

2. lenght in loop

3. flip()function

4. reverse function

5. flipup()function

6. fliplr() function

Example of 1D and 2D array is





In [79]:
import numpy as np
#create 1D array
array = np.array([4, 5 , 6, 7])
print(array)

[4 5 6 7]


In [80]:
import numpy as np

# create 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)

[[1 2 3]
 [4 5 6]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.


Answer: The data type of elements in a numpy array provide a rich set of data types that can be used to create arrays with different types of elements.

The improtance of data types in memory management and performance is in numpy data types are simillar to,but not ecactly the same as python data types.



5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?


Answer: The core of NumPy package is the ndarrays in NumPy, it encapsulates n-dimensional arrays of homogeneous data types  with many operations being performed in complied code for performance.


They differ from standard python lists by-

1. NumPy arrays have a fixed size at creations ,unlike python lists . Changing the sixe of an ndarray will create a new array and delete the original.

2. The elemnets in a NumPy array are all required to be of the same data type and will be the same size in memory.


3. NumPy arrays facillitate advanced mathametical and other types of operation on large numbers of data.

4. A growing plethora of scientific and mathemetical pthon based package are using NumPy arrays,through these typically support python sequence input, they convert such input to NumPy arrays prior to processing and they often output NumPy arrays.


6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Answer:  The performance benefits of numpy arrays over python lists for large scale numerical operations is-

its provides significant speed advantages over list .

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.


Answer:vstack functions - it is view in vertical line.


hstack functions- it is view in horizontal line.


Example



In [77]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = np.hstack((array1, array2))
print(result)


[1 2 3 4 5 6]


In [76]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = np.vstack((array1, array2))
print(result)

[[1 2 3]
 [4 5 6]]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Answer:the differecnce between fliplr() and flipup() methods in numpy , including their effects on various array dimensions -

fliplr() method-it is used to reverse the order of elements along axis 1

fluipup() method -it is used to reverse the order of elements along axis 0.

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Answer:The functionality of array_split()method is the splitting involves dividing an array into multiple sub-arrays along a specified axis.




10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?


Answer: The concepts of vectorization operations enable performing element wise operations on entire arrays without explict looping.


This leads to more concise and efficient code.

PRACTICAL QUESTION

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np
array_3x3 = np.random.randint(1, 101, size = (3,3))
print("original array:")
print(array_3x3)

#interchanged rows and columns
interchanged_array = array_3x3.T

print("\narray with interchanged rows and columns:")
interchanged_array




original array:
[[18  8 87]
 [69 40  6]
 [59  5 73]]

array with interchanged rows and columns:


array([[18, 69, 59],
       [ 8, 40,  5],
       [87,  6, 73]])

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [15]:
import numpy as np
#create an array from 10 elements
array_1D = np.arange(10)

#create a 1D array using 2*5
array_2x5 = array_1D.reshape(2, 5)
print("2x5 array:\n", array_2x5)

#create a 1D array reshape it by using 5*2
array_5x2 = array_1D.reshape(5, 2)
print("5x2 array:\n", array_5x2)


2x5 array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [19]:
import numpy as np
#create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

#Add a border zero
array_6x6 =np.pad(array_4x4, pad_width = 1, mode = 'constant', constant_values = 0)

print("original array_6x6")
array_6x6


original array_6x6


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.54868547, 0.4880244 , 0.0714535 , 0.71934824,
        0.        ],
       [0.        , 0.05579987, 0.07280496, 0.61195253, 0.68992529,
        0.        ],
       [0.        , 0.38431095, 0.71753924, 0.73957193, 0.31033656,
        0.        ],
       [0.        , 0.84127648, 0.27498071, 0.25874688, 0.59984708,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.


In [23]:
import numpy as np

# create an array of intergers from 10 to 60 with a 5 steps
array_step_5 = np.arange(10, 61, 5)
array_step_5

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element

In [26]:
import numpy as np

#create numpy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])
#apply uppercase transformation
uppercase_array = np.char.upper(string_array)
print("uppercase:", uppercase_array)


uppercase: ['PYTHON' 'NUMPY' 'PANDAS']


In [28]:
#create numpy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])
#apply lowercase transformation
lowercase_array = np.char.lower(string_array)
print("lowerrcase:", lowercase_array)


lowerrcase: ['python' 'numpy' 'pandas']


In [29]:
#create numpy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])
#apply titlecase transformation
titlecase_array = np.char.title(string_array)
print("titlecase:", titlecase_array)


titlecase: ['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [35]:
import numpy as np
word_array = np.array(['Apple', 'Orange'])

#insert a linspace in each word
spaced_word = np.char.join(' ', word_array)
spaced_word

array(['A p p l e', 'O r a n g e'], dtype='<U11')

7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [47]:
import numpy as np
#create 2d numpy array
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition_result = array1 + array2
print("Addition:\n", addition_result)



Addition:
 [[ 8 10 12]
 [14 16 18]]


In [48]:
# Element-wise substraction
substraction_result = array1 + array2
print("substraction:\n", substraction_result)

substraction:
 [[ 8 10 12]
 [14 16 18]]


In [50]:
# Element-wise multiplication
multiplication_result = array1 + array2
print("multiplication:\n", multiplication_result)

multiplication:
 [[ 8 10 12]
 [14 16 18]]


In [51]:
# Element-wise division
division_result = array1 + array2
print("division:\n", division_result)

division:
 [[ 8 10 12]
 [14 16 18]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [54]:
import numpy as np
#create a 5x5 identity matrix
identity_matrix = np.eye(5)
# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:\n", diagonal_elements)


Diagonal Elements:
 [1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [58]:
import numpy as np

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

#generate a numpy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size = 100)
# find and display all prine numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]
print("prime numbers in the array:", prime_numbers)

prime numbers in the array: [41, 733, 173, 17, 491, 487, 397, 83, 733, 349, 997, 419, 41, 173]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [81]:
#create a numpy array of daily temperature for a month
temperatures = np.random.randint(25,40, size=30)
weekly_averages = []
#calculate weekly averages
for i in range (0, 30, 7):
  week_temps = temperatures[i:min(i + 7, 30)]
  weekly_average = np.mean(week_temps)
  weekly_averages.append(weekly_average)
# display the weekly averages
print("weekly average temperatures:")
for i, avg in enumerate(weekly_averages):
  print(f"Week {i + 1}: {avg:.2f}")

weekly average temperatures:
Week 1: 33.00
Week 2: 30.29
Week 3: 32.00
Week 4: 29.14
Week 5: 29.50
